language: php

php:
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"


before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - composer install

script:
  - ./vendor/bin/phpunit
  - ./travis/smoketest.sh
